# .project metadata for hami
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "hami"
name: "hami"
description: "Heterogeneous AI Computing Virtualization Middleware"
type: "project"
project_lead: "archlitchi"
cncf_slack_channel: "#C07T10BU4R2"

maturity_log:
  - phase: "sandbox"
    date: "2024-08-21T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/132" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/Project-HAMi/HAMi"

website: "https://project-hami.github.io/HAMi/"

artwork: "https://landscape.cncf.io/logos/hami.svg"

adopters:
  path: "https://github.com/Project-HAMi/.project/blob/main/ADOPTERS.md"

package_managers:
   docker: "projecthami/hami"


security:
  policy:
    path: "https://github.com/Project-HAMi/HAMi/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/Project-HAMi/HAMi/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/Project-HAMi/HAMi/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/Project-HAMi/HAMi/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/Project-HAMi/HAMi/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/Project-HAMi/HAMi/blob/main/README.md"

landscape:
  category: "Orchestration & Management"
  subcategory: "Scheduling & Orchestration"

# CLOMonitor Score: 80/100
# Documentation: 87 | License: 100 | Best Practices: 68 | Security: 60
